version: '3'

services:
  server:
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ADMIN_JWT_SECRET=secret
      - ADMIN_EMAILS=john@example.com,admin@example.com
      - CUSTOMER_JWT_SECRET=secret
    ports:
      - 3000:3000
