version: '3'

services:
  server:
    build: .
    environment:
      - HOST=server
      - PORT=3000
      - ADMIN_JWT_SECRET=secret
      - ADMIN_EMAILS=john@example.com,admin@example.com
      - CUSTOMER_JWT_SECRET=secret
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
