name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm start &
      env:
        HOST: 0.0.0.0
        PORT: 3000
        ADMIN_JWT_SECRET: secret
        ADMIN_EMAILS: john@example.com,admin@example.com
        CUSTOMER_JWT_SECRET: secret
    - run: npm test
